apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k1s-operator-k1s-dev-a-reader
  namespace: k1s-dev-a
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
