apiVersion: operator.k1s.io/v1alpha1
kind: K1sCluster
metadata:
  name: edge-a
  namespace: k1s-operator-system
spec:
  controller:
    url: https://k1s-controller.k1s-system.svc:9108
  apishim:
    url: https://k1s-apishim.k1s-system.svc:8445
  authSecretRef:
    name: k1s-edge-a-operator
    namespace: k1s-operator-system
    controllerReadTokenKey: controllerReadToken
    controllerWriteTokenKey: controllerWriteToken
    caBundleKey: ca.crt
  proxy:
    mode: Service
    serviceRef:
      name: k1s-edge-proxy
      namespace: k1s-system
      port: 10080
  pollIntervalSeconds: 15
