//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionedStatus) DeepCopyInto(out *ConditionedStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionedStatus.
func (in *ConditionedStatus) DeepCopy() *ConditionedStatus {
	if in == nil {
		return nil
	}
	out := new(ConditionedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sApp) DeepCopyInto(out *K1sApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sApp.
func (in *K1sApp) DeepCopy() *K1sApp {
	if in == nil {
		return nil
	}
	out := new(K1sApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppList) DeepCopyInto(out *K1sAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K1sApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppList.
func (in *K1sAppList) DeepCopy() *K1sAppList {
	if in == nil {
		return nil
	}
	out := new(K1sAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppMirror) DeepCopyInto(out *K1sAppMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppMirror.
func (in *K1sAppMirror) DeepCopy() *K1sAppMirror {
	if in == nil {
		return nil
	}
	out := new(K1sAppMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sAppMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppMirrorList) DeepCopyInto(out *K1sAppMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K1sAppMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppMirrorList.
func (in *K1sAppMirrorList) DeepCopy() *K1sAppMirrorList {
	if in == nil {
		return nil
	}
	out := new(K1sAppMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sAppMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppMirrorSpec) DeepCopyInto(out *K1sAppMirrorSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.AppRef = in.AppRef
	if in.ExposureRef != nil {
		in, out := &in.ExposureRef, &out.ExposureRef
		*out = new(NamespacedNameRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppMirrorSpec.
func (in *K1sAppMirrorSpec) DeepCopy() *K1sAppMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(K1sAppMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppMirrorStatus) DeepCopyInto(out *K1sAppMirrorStatus) {
	*out = *in
	out.Replicas = in.Replicas
	if in.Placements != nil {
		in, out := &in.Placements, &out.Placements
		*out = make([]K1sPlacementStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppMirrorStatus.
func (in *K1sAppMirrorStatus) DeepCopy() *K1sAppMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(K1sAppMirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppRef) DeepCopyInto(out *K1sAppRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppRef.
func (in *K1sAppRef) DeepCopy() *K1sAppRef {
	if in == nil {
		return nil
	}
	out := new(K1sAppRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppSpec) DeepCopyInto(out *K1sAppSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	in.Manifest.DeepCopyInto(&out.Manifest)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppSpec.
func (in *K1sAppSpec) DeepCopy() *K1sAppSpec {
	if in == nil {
		return nil
	}
	out := new(K1sAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAppStatus) DeepCopyInto(out *K1sAppStatus) {
	*out = *in
	out.Replicas = in.Replicas
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAppStatus.
func (in *K1sAppStatus) DeepCopy() *K1sAppStatus {
	if in == nil {
		return nil
	}
	out := new(K1sAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sAuthSecretRef) DeepCopyInto(out *K1sAuthSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sAuthSecretRef.
func (in *K1sAuthSecretRef) DeepCopy() *K1sAuthSecretRef {
	if in == nil {
		return nil
	}
	out := new(K1sAuthSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sCluster) DeepCopyInto(out *K1sCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sCluster.
func (in *K1sCluster) DeepCopy() *K1sCluster {
	if in == nil {
		return nil
	}
	out := new(K1sCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sClusterList) DeepCopyInto(out *K1sClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K1sCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sClusterList.
func (in *K1sClusterList) DeepCopy() *K1sClusterList {
	if in == nil {
		return nil
	}
	out := new(K1sClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sClusterSpec) DeepCopyInto(out *K1sClusterSpec) {
	*out = *in
	out.Controller = in.Controller
	if in.Apishim != nil {
		in, out := &in.Apishim, &out.Apishim
		*out = new(K1sEndpointSpec)
		**out = **in
	}
	if in.BootstrapConfigMapRef != nil {
		in, out := &in.BootstrapConfigMapRef, &out.BootstrapConfigMapRef
		*out = new(NamespacedNameRef)
		**out = **in
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(K1sAuthSecretRef)
		**out = **in
	}
	in.Proxy.DeepCopyInto(&out.Proxy)
	if in.PollIntervalSeconds != nil {
		in, out := &in.PollIntervalSeconds, &out.PollIntervalSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sClusterSpec.
func (in *K1sClusterSpec) DeepCopy() *K1sClusterSpec {
	if in == nil {
		return nil
	}
	out := new(K1sClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sClusterStatus) DeepCopyInto(out *K1sClusterStatus) {
	*out = *in
	out.NodeSummary = in.NodeSummary
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sClusterStatus.
func (in *K1sClusterStatus) DeepCopy() *K1sClusterStatus {
	if in == nil {
		return nil
	}
	out := new(K1sClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sEndpointSpec) DeepCopyInto(out *K1sEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sEndpointSpec.
func (in *K1sEndpointSpec) DeepCopy() *K1sEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(K1sEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sExposure) DeepCopyInto(out *K1sExposure) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sExposure.
func (in *K1sExposure) DeepCopy() *K1sExposure {
	if in == nil {
		return nil
	}
	out := new(K1sExposure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sExposure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sExposureIngressSpec) DeepCopyInto(out *K1sExposureIngressSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sExposureIngressSpec.
func (in *K1sExposureIngressSpec) DeepCopy() *K1sExposureIngressSpec {
	if in == nil {
		return nil
	}
	out := new(K1sExposureIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sExposureList) DeepCopyInto(out *K1sExposureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K1sExposure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sExposureList.
func (in *K1sExposureList) DeepCopy() *K1sExposureList {
	if in == nil {
		return nil
	}
	out := new(K1sExposureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sExposureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sExposureServiceSpec) DeepCopyInto(out *K1sExposureServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sExposureServiceSpec.
func (in *K1sExposureServiceSpec) DeepCopy() *K1sExposureServiceSpec {
	if in == nil {
		return nil
	}
	out := new(K1sExposureServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sExposureSpec) DeepCopyInto(out *K1sExposureSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.AppRef = in.AppRef
	out.Service = in.Service
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.TrafficProbe.DeepCopyInto(&out.TrafficProbe)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sExposureSpec.
func (in *K1sExposureSpec) DeepCopy() *K1sExposureSpec {
	if in == nil {
		return nil
	}
	out := new(K1sExposureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sExposureStatus) DeepCopyInto(out *K1sExposureStatus) {
	*out = *in
	if in.LastAppSyncTime != nil {
		in, out := &in.LastAppSyncTime, &out.LastAppSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sExposureStatus.
func (in *K1sExposureStatus) DeepCopy() *K1sExposureStatus {
	if in == nil {
		return nil
	}
	out := new(K1sExposureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sExposureTrafficProbeSpec) DeepCopyInto(out *K1sExposureTrafficProbeSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sExposureTrafficProbeSpec.
func (in *K1sExposureTrafficProbeSpec) DeepCopy() *K1sExposureTrafficProbeSpec {
	if in == nil {
		return nil
	}
	out := new(K1sExposureTrafficProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceCellSetSpec) DeepCopyInto(out *K1sInferenceCellSetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceCellSetSpec.
func (in *K1sInferenceCellSetSpec) DeepCopy() *K1sInferenceCellSetSpec {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceCellSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceEndpoint) DeepCopyInto(out *K1sInferenceEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceEndpoint.
func (in *K1sInferenceEndpoint) DeepCopy() *K1sInferenceEndpoint {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sInferenceEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceEndpointList) DeepCopyInto(out *K1sInferenceEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K1sInferenceEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceEndpointList.
func (in *K1sInferenceEndpointList) DeepCopy() *K1sInferenceEndpointList {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sInferenceEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceEndpointSpec) DeepCopyInto(out *K1sInferenceEndpointSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.Model = in.Model
	out.Parallelism = in.Parallelism
	out.Executor = in.Executor
	out.Fabric = in.Fabric
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]K1sInferenceMemberSpec, len(*in))
		copy(*out, *in)
	}
	if in.CellSet != nil {
		in, out := &in.CellSet, &out.CellSet
		*out = new(K1sInferenceCellSetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceEndpointSpec.
func (in *K1sInferenceEndpointSpec) DeepCopy() *K1sInferenceEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceEndpointStatus) DeepCopyInto(out *K1sInferenceEndpointStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceEndpointStatus.
func (in *K1sInferenceEndpointStatus) DeepCopy() *K1sInferenceEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceExecutorSpec) DeepCopyInto(out *K1sInferenceExecutorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceExecutorSpec.
func (in *K1sInferenceExecutorSpec) DeepCopy() *K1sInferenceExecutorSpec {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceExecutorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceFabricSpec) DeepCopyInto(out *K1sInferenceFabricSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceFabricSpec.
func (in *K1sInferenceFabricSpec) DeepCopy() *K1sInferenceFabricSpec {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceFabricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceMemberSpec) DeepCopyInto(out *K1sInferenceMemberSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceMemberSpec.
func (in *K1sInferenceMemberSpec) DeepCopy() *K1sInferenceMemberSpec {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceModelSpec) DeepCopyInto(out *K1sInferenceModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceModelSpec.
func (in *K1sInferenceModelSpec) DeepCopy() *K1sInferenceModelSpec {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sInferenceParallelismSpec) DeepCopyInto(out *K1sInferenceParallelismSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sInferenceParallelismSpec.
func (in *K1sInferenceParallelismSpec) DeepCopy() *K1sInferenceParallelismSpec {
	if in == nil {
		return nil
	}
	out := new(K1sInferenceParallelismSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sManagedResourceStatus) DeepCopyInto(out *K1sManagedResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sManagedResourceStatus.
func (in *K1sManagedResourceStatus) DeepCopy() *K1sManagedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(K1sManagedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sNodeSummary) DeepCopyInto(out *K1sNodeSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sNodeSummary.
func (in *K1sNodeSummary) DeepCopy() *K1sNodeSummary {
	if in == nil {
		return nil
	}
	out := new(K1sNodeSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sPlacementStatus) DeepCopyInto(out *K1sPlacementStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sPlacementStatus.
func (in *K1sPlacementStatus) DeepCopy() *K1sPlacementStatus {
	if in == nil {
		return nil
	}
	out := new(K1sPlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sProxyExternalSpec) DeepCopyInto(out *K1sProxyExternalSpec) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sProxyExternalSpec.
func (in *K1sProxyExternalSpec) DeepCopy() *K1sProxyExternalSpec {
	if in == nil {
		return nil
	}
	out := new(K1sProxyExternalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sProxyServiceRef) DeepCopyInto(out *K1sProxyServiceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sProxyServiceRef.
func (in *K1sProxyServiceRef) DeepCopy() *K1sProxyServiceRef {
	if in == nil {
		return nil
	}
	out := new(K1sProxyServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sProxySpec) DeepCopyInto(out *K1sProxySpec) {
	*out = *in
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(K1sProxyServiceRef)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(K1sProxyExternalSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sProxySpec.
func (in *K1sProxySpec) DeepCopy() *K1sProxySpec {
	if in == nil {
		return nil
	}
	out := new(K1sProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sReplicaSummary) DeepCopyInto(out *K1sReplicaSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sReplicaSummary.
func (in *K1sReplicaSummary) DeepCopy() *K1sReplicaSummary {
	if in == nil {
		return nil
	}
	out := new(K1sReplicaSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sResourceSet) DeepCopyInto(out *K1sResourceSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sResourceSet.
func (in *K1sResourceSet) DeepCopy() *K1sResourceSet {
	if in == nil {
		return nil
	}
	out := new(K1sResourceSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sResourceSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sResourceSetList) DeepCopyInto(out *K1sResourceSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K1sResourceSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sResourceSetList.
func (in *K1sResourceSetList) DeepCopy() *K1sResourceSetList {
	if in == nil {
		return nil
	}
	out := new(K1sResourceSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K1sResourceSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sResourceSetSpec) DeepCopyInto(out *K1sResourceSetSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowedKinds != nil {
		in, out := &in.AllowedKinds, &out.AllowedKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sResourceSetSpec.
func (in *K1sResourceSetSpec) DeepCopy() *K1sResourceSetSpec {
	if in == nil {
		return nil
	}
	out := new(K1sResourceSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K1sResourceSetStatus) DeepCopyInto(out *K1sResourceSetStatus) {
	*out = *in
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]K1sManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K1sResourceSetStatus.
func (in *K1sResourceSetStatus) DeepCopy() *K1sResourceSetStatus {
	if in == nil {
		return nil
	}
	out := new(K1sResourceSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedNameRef) DeepCopyInto(out *NamespacedNameRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedNameRef.
func (in *NamespacedNameRef) DeepCopy() *NamespacedNameRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedNameRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativeManifest) DeepCopyInto(out *NativeManifest) {
	*out = *in
	in.Raw.DeepCopyInto(&out.Raw)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativeManifest.
func (in *NativeManifest) DeepCopy() *NativeManifest {
	if in == nil {
		return nil
	}
	out := new(NativeManifest)
	in.DeepCopyInto(out)
	return out
}
